openapi: 3.0.0
info:
  title: biobb Analysis interface
  version: '0.1'
servers:
  - url: 'http://mmb.irbbarcelona.org/api/v0.1/biobb_analysis'
paths:
  /rms:
    post:
      operationId: rms
      description: Wrapper of the GROMACS rms (http://manual.gromacs.org/current/onlinehelp/gmx-rms.html) module interface
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/rms'
      responses:
        '200':
          description: stdout and stderr from operations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/logs'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  /cluster:
    post:
      operationId: cluster
      description: MWrapper class for the GROMACS cluster (http://manual.gromacs.org/current/onlinehelp/gmx-cluster.html) module
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/cluster'
      responses:
        '200':
          description: stdout and stderr from operations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/logs'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  /cpptraj:
    post:
      operationId: cpptraj
      description: Wrapper of the Ambertools Cpptraj module. Cpptraj (the successor to ptraj) is the main program in Amber for processing coordinate trajectories and data files. The parameter names and defaults are the same as the ones in the official Cpptraj 'https://amber-md.github.io/cpptraj/CPPTRAJ.xhtm'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/cpptraj'
      responses:
        '200':
          description: stdout and stderr from operations
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/logs'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  
components:
  schemas:
    rms:
      title: 'Wrapper of the GROMACS rms (http://manual.gromacs.org/current/onlinehelp/gmx-rms.html) module'
      type: object
      required:
        - input_structure_path
        - input_traj_path
        - output_xvg_path
      properties:
        input_structure_path:
          type: string
          description: Path to the input GRO/PDB/TPR file
        input_traj_path:
          type: string
          description: Path to the GROMACS trajectory file XTC/TRR
        output_xvg_path:
          type: string
          description: Path to the XVG output file
        properties:
          type: object
          properties:
            xvg:
              type: string
              default: none
              description: XVG plot formatting
              enum:
                - xmgrace
                - xmgr
                - none
            selection:
              type: string
              default: Protein-H
              description: Group where the rms will be performed
              enum:
                - System
                - Protein
                - Protein-H
                - ...
            gmx_path:
              type: string
              default: gmx
              description: Path to the GROMACS executable binary
      additionalProperties: false
    cluster:
      title: 'Wrapper class for the GROMACS cluster (http://manual.gromacs.org/current/onlinehelp/gmx-cluster.html) module'
      type: object
      required:
        - input_gro_path
        - input_traj_path
        - output_pdb_path
      properties:
        input_gro_path:
          type: string
          description: Path to the initial GROMACS structure file GRO.
        input_traj_path:
          type: string
          description: 'Path to the GROMACS trajectory: TRR or XTC formats.'
        output_pdb_path:
          type: string
          description: Path to the output cluster PDB file
        properties:
          type: object
          properties:
            dista:
              type: boolean
              default: false
              description: Use RMSD of distances instead of RMS deviation
            method:
              type: string
              default: linkage
              description: Method for cluster determination
              enum:
                - linkage
                - jarvis-patrick
                - monte-carlo
                - diagonalization
                - gromos
            cutoff:
              type: number
              default: 0.1
              description: RMSD cut-off (nm) for two structures to be neighbors
            gmx_path:
              type: string
              default: gmx
              description: Path to the GROMACS executable binary
      additionalProperties: false
    cpptraj:
      title: 'Wrapper of the Ambertools Cpptraj module. Cpptraj (the successor to ptraj) is the main program in Amber for processing coordinate trajectories and data files. The parameter names and defaults are the same as the ones in the official Cpptraj manual: https://amber-md.github.io/cpptraj/CPPTRAJ.xhtm'
      type: object
      required:
        - input_top_path
        - input_traj_path
        - output_dat_path
        - output_traj_path
      properties:
        input_top_path:
          type: string
          description: Path to the input Amber structure or topology file
        input_traj_path:
          type: string
          description: Path to the input Amber trajectory to be processed
        output_dat_path:
          type: string
          description: Path to the output dat file containing the analysis results
        output_traj_path:
          type: string
          description: Path to the output processed Amber trajectory
        properties:
          type: object
          properties:
            input_instructions_path:
              type: string
              default: None
              description: Path of the input file
            input_instructions:
              type: object
              description: Input options specification. (Used if input_file_path is None)
              properties:
                analysis:
                  type: string
                  default: rms
                  description: Default options for the input instructions file. Valid values
                  enum:
                    - rms
                    - undefined
            output_instructions_path:
              type: string
              default: instructions.in
              description: Path of the instructions file to be created
            cpptraj_path:
              type: string
              default: cpptraj
              description: Path to the cpptraj executable binary
      additionalProperties: false
    logs:
      type: object
      required:
        - stdout
        - stderr
      properties:
        stdout:
          type: string
          description: Redirected standard out from operations
        stderr:
          type: string
          description: Redirected standard     error from operations
    error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
